// Package main boots the HTTP server and also hosts Swagger metadata for API docs.
//
// @title           City Service API
// @version         1.0
// @description     REST API for City Service — city request management platform
// @host            city-service-production.up.railway.app
// @Schemes         https
// @BasePath        /api
// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
// @description     Paste your JWT token like: Bearer eyJhbG...
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"city-service/internal/config"
	"city-service/internal/handler"
	"city-service/internal/middleware"
	"city-service/internal/repository"
	"city-service/internal/service"
	"city-service/pkg/logger"
	miniopkg "city-service/pkg/minio"
	httpSwagger "github.com/swaggo/http-swagger"

	"github.com/go-chi/chi/v5"
	chimw "github.com/go-chi/chi/v5/middleware"
	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	"github.com/jmoiron/sqlx"

	// docs is generated by Swag CLI (swag init) and provides Swagger metadata.
	_ "city-service/docs"

	_ "github.com/jackc/pgx/v5/stdlib" // registers "pgx" database/sql driver
)

func main() {
	log := logger.New()

	// 1. Load config from .env/environment.
	cfg, err := config.Load()
	if err != nil {
		log.Error("config load failed", slog.String("error", err.Error()))
		os.Exit(1)
	}

	// 2. Connect to PostgreSQL.
	db, err := sqlx.Connect("pgx", cfg.DBURL)
	if err != nil {
		log.Error("db connect failed", slog.String("error", err.Error()))
		os.Exit(1)
	}
	defer db.Close()

	// 3. Run migrations automatically.
	if err := runMigrations(db); err != nil {
		log.Error("migrations failed", slog.String("error", err.Error()))
		os.Exit(1)
	}

	// 4. Connect to MinIO, ensure bucket exists.
	// minioClient, err := miniopkg.NewMinioClient(cfg)
	// if err != nil {
	// 	log.Error("minio init failed", slog.String("error", err.Error()))
	// 	os.Exit(1)
	// }
	var minioClient *miniopkg.Client
	if cfg.MinioEndpoint != "" {
		minioClient, err = miniopkg.NewMinioClient(cfg)
		if err != nil {
			log.Warn("minio init failed, file uploads disabled", slog.String("error", err.Error()))
		}
	}

	// 5. Initialize repositories (DB only).
	userRepo := repository.NewUserRepo(db)
	categoryRepo := repository.NewCategoryRepo(db)
	requestRepo := repository.NewRequestRepo(db)
	cancellationRepo := repository.NewCancellationRepo(db)
	completionRepo := repository.NewCompletionRepo(db)

	// 6. Initialize services (business logic only).
	authSvc := service.NewAuthService(userRepo, cfg.JWTSecret, cfg.JWTExpiry)
	categorySvc := service.NewCategoryService(categoryRepo)
	requestSvc := service.NewRequestService(requestRepo, categoryRepo, cancellationRepo, minioClient, cfg.MinioBucket)
	completionSvc := service.NewCompletionService(requestRepo, completionRepo, minioClient, cfg.MinioBucket)

	// 7. Initialize handlers (HTTP only).
	authHandler := handler.NewAuthHandler(authSvc)
	categoryHandler := handler.NewCategoryHandler(categorySvc)
	requestHandler := handler.NewRequestHandler(requestSvc)
	contractorHandler := handler.NewContractorHandler(requestSvc, completionSvc)
	adminHandler := handler.NewAdminHandler(requestSvc, categorySvc)

	// 8. Setup Chi router with middleware.
	r := chi.NewRouter()
	r.Use(chimw.RequestID)
	r.Use(chimw.RealIP)
	r.Use(chimw.Recoverer)
	r.Use(chimw.Logger)

	authMW := middleware.NewAuthMiddleware(userRepo, cfg.JWTSecret)

	// Swagger UI endpoint (not under /api so it's easy to discover in browser).
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// 9. Register all API routes.
	r.Route("/api", func(r chi.Router) {
		// Public
		r.Post("/auth/register", authHandler.Register)
		r.Post("/auth/login", authHandler.Login)
		r.Get("/categories", categoryHandler.List)

		// Monitor routes
		r.Group(func(r chi.Router) {
			r.Use(authMW.Authenticate)
			r.Use(middleware.RequireRole("monitor"))
			r.Get("/requests", requestHandler.List)
			r.Get("/requests/my", requestHandler.MyRequests)
			r.Get("/requests/{id}", requestHandler.GetByID)
			r.Post("/requests", requestHandler.Create)
			r.Post("/requests/{id}/cancel", requestHandler.Cancel)
		})

		// Contractor routes
		r.Group(func(r chi.Router) {
			r.Use(authMW.Authenticate)
			r.Use(middleware.RequireRole("contractor"))
			r.Get("/contractor/requests", contractorHandler.List)
			r.Get("/contractor/requests/my", contractorHandler.MyRequests)
			r.Get("/contractor/requests/{id}", contractorHandler.GetByID)
			r.Post("/contractor/requests/{id}/take", contractorHandler.Take)
			r.Post("/contractor/requests/{id}/complete", contractorHandler.Complete)
		})

		// Admin routes
		r.Group(func(r chi.Router) {
			r.Use(authMW.Authenticate)
			r.Use(middleware.RequireRole("admin"))
			r.Get("/admin/requests", adminHandler.ListAll)
			r.Get("/admin/stats", adminHandler.Stats)
		})
	})

	// 10. Start HTTP server.
	srv := &http.Server{
		Addr:              ":" + cfg.Port,
		Handler:           r,
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		log.Info("server started", slog.String("addr", srv.Addr))
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Error("server crashed", slog.String("error", err.Error()))
		}
	}()

	// 11. Graceful shutdown on SIGINT/SIGTERM.
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)
	<-stop

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	log.Info("shutting down")
	_ = srv.Shutdown(ctx)
}

func runMigrations(db *sqlx.DB) error {
	driver, err := postgres.WithInstance(db.DB, &postgres.Config{})
	if err != nil {
		return err
	}

	// file://migrations works when you run from repo root.
	m, err := migrate.NewWithDatabaseInstance("file://migrations", "postgres", driver)
	if err != nil {
		return err
	}

	if err := m.Up(); err != nil && !errors.Is(err, migrate.ErrNoChange) {
		return err
	}
	return nil
}

